services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Leo123
      - MONGO_INITDB_DATABASE=products
    volumes:
      - ./data:/data/db
    networks:
      - my_network


  product:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product
    ports:
      - "8018:8018"
    depends_on:
      - mongodb
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
